# Generated by Django 3.0 on 2021-11-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(max_length=1000)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
